### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by ramiror** [JosefZIla/bash2048#11]
It's a bit slow for larger grids (20x20).
It could be improved by avoiding $(command), which creates a subshell. Most importantly within tight loops.

Example of performance improvement:

```
182 function apply_push {
183   printf "\n\ninput: $1 key\n" >&3
184   declare -i i=0
185   while [ $i -le $index_max ]; do
186     declare -i j=0
187     while [ $j -le $index_max ]; do
188       flag_skip=0
189       let increment_max=index_max-j
190       declare -i k=1
191       while [ $k -le $increment_max ]; do
192         let flag_skip && break
193         push_pieces $i $j $k $1 $2
194         k=$k+1
195       done~
196       j=$j+1
197     done
198     i=$i+1
199   done
```

**Comment by SingChia** [comment]
I'm beginner for bash, your program redirect some information to fd 3, what's that for? and i tried `tail -f /proc/pid/fd/3`, nothing prints

**Comment by mydzor** [comment]
I use FD 3 for logs, it is set during commandline option parsing, see [https://github.com/mydzor/bash2048/blob/master/bash2048.sh#L329](url)

**Comment by JosefZIla** [comment]
sorry, I will not be updating this game anymore, so I am closing this issue.
