### ISSUE TITLE
First time playing!

### ISSUE THREAD

**Issue by jaredmichaelwilliams** [JosefZIla/bash2048#24]
[I think I did pretty well](http://i.imgur.com/9PekiHo.png)

**Comment by artur309** [comment]
Yeh me too, very nice script xD

**Comment by meyt** [comment]
![image](https://user-images.githubusercontent.com/10482278/61479682-940da480-a9a9-11e9-92fd-b60b76cfd519.png)

**Comment by JosefZIla** [comment]
cool :)
